name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches: [main]
    paths-ignore:
      - '.github/**' # We don't want to trigger when we update the workflows.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      # This is an example of running a docker-action
    - name: Docker Action (local)
      uses: ./.github/actions/example-docker

      # This action uses a versioned tag for pinning, it's secure right?!?
    - name: Docker Action (remote)
      id: docker-action
      uses: tdonaworth/gha-digest-pinning-poc-docker-action@v2.0
      #uses: tdonaworth/gha-digest-pinning-poc-docker-action@0552a8d3c45459bf5b7332525a853aaaeab9ee92 # v1.1.0

    